language: python

python:
  - "2.7"

env: LIBGIT2=~/libgit2/_install/ LD_LIBRARY_PATH=~/libgit2/_install/lib

before_install:
  - sudo apt-get install cmake
  - pip install cffi
  - "./.travis.sh"

script:
  - trial bitwrap_storage_pygit2.test
